apiVersion: account.snowflake.com/v1alpha1
kind: AccountRole
metadata:
  annotations:
    meta.upbound.io/example-id: account/v1alpha1/accountrole
  labels:
    testing.upbound.io/example-name: minimal
  name: minimal
spec:
  forProvider:
    name: role_name
