apiVersion: v1
kind: Namespace
metadata:
  name: crossplane-system
---
apiVersion: snowflake.crossplane.io/v1alpha1
kind: ProviderConfig
metadata:
  name: example
spec:
  snowflakeAccount: volvocars-manufacturinganalytics
  username: HHARPREE@VOLVOCARS.COM 
  credentials:
    source: Secret
    secretRef:
      namespace: default
      name: sw-secret
      key: pkey
  fingerPrint:
    source: Secret
    secretRef:
      namespace: default
      name: sw-secret
      key: fkey
